version: '3.6'
services:
  siag:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - type: bind
        source: .
        target: /var/www/html/
    