version: '3.6'
services:
  siag:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8081:80
    volumes:
      - type: bind
        source: .
        target: /var/www/html/
    