version: "3"
services:
  nodejs:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile-nodejs
    networks:
      - mongodb_default
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3333:3333

networks:
  mongodb_default:
    external: true