version: '3'
services:
  react:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/workspace:cached
      command: /bin/sh -c "while sleep 1000; do :; done"
      network_mode: host
      ports: 
        - 3000:3000
        - 5000:5000